platform :ios, '8.0'
#source 'https://github.com/CocoaPods/Specs.git'
source 'https://mirrors.tuna.tsinghua.edu.cn/git/CocoaPods/Specs.git'
target 'HQJBusiness' do

pod 'AFNetworking', '~> 3.1.0'

pod 'SDCycleScrollView', '~> 1.64'

pod 'SDAutoLayout', '~> 2.1.1'

pod 'SDWebImage', '~> 3.7.6'

pod 'MJRefresh', '~> 3.1.0'

pod 'SVProgressHUD'

pod 'IQKeyboardManager'

#pod 'ZBarSDK', '~> 1.3.1'
pod 'LBXZBarSDK','~> 1.3'

pod 'DZNEmptyDataSet'

pod 'MJExtension'

pod 'FDFullscreenPopGesture', '1.1'

pod 'Masonry'

pod 'JKCountDownButton'

pod 'SWTableViewCell', '~> 0.3.7'
pod 'UMCCommon'
pod 'UMengUShare/UI'      # U-Share SDK UI模块
pod 'UMengUShare/Social/ReducedWeChat'  # 集成微信(精简版0.2M)
use_frameworks!

#pod 'ReactiveObjC'
pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'
pod 'JPush'
pod "NSDictionary-NilSafe"

end
