platform :ios, '8.0'
target 'HQJBusiness' do

pod 'AFNetworking', '~> 3.1.0'

pod 'SDCycleScrollView', '~> 1.64'

pod 'SDAutoLayout', '~> 2.1.1'

pod 'SDWebImage', '~> 3.7.6'

pod 'MJRefresh', '~> 3.1.0'

pod 'SVProgressHUD'

pod 'IQKeyboardManager'

pod 'ZBarSDK', '~> 1.3.1'

pod 'DZNEmptyDataSet'

pod 'MJExtension'

pod 'FDFullscreenPopGesture', '1.1'

pod 'Masonry'

pod 'JKCountDownButton'

pod 'SWTableViewCell', '~> 0.3.7'

use_frameworks!

pod 'ReactiveCocoa', :git => 'https://github.com/zhao0/ReactiveCocoa.git', :tag => '2.5.2'


end
